//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hospital_mgmt_CEFC.CEFCServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Class_Patient", Namespace="http://schemas.datacontract.org/2004/07/HospitalCEFCService")]
    [System.SerializableAttribute()]
    public partial class Class_Patient : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime PdisDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PempIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime PregDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PremarksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PsexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string patientNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int patientNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Paddress {
            get {
                return this.PaddressField;
            }
            set {
                if ((object.ReferenceEquals(this.PaddressField, value) != true)) {
                    this.PaddressField = value;
                    this.RaisePropertyChanged("Paddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Page {
            get {
                return this.PageField;
            }
            set {
                if ((this.PageField.Equals(value) != true)) {
                    this.PageField = value;
                    this.RaisePropertyChanged("Page");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PdisDate {
            get {
                return this.PdisDateField;
            }
            set {
                if ((this.PdisDateField.Equals(value) != true)) {
                    this.PdisDateField = value;
                    this.RaisePropertyChanged("PdisDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PempID {
            get {
                return this.PempIDField;
            }
            set {
                if ((this.PempIDField.Equals(value) != true)) {
                    this.PempIDField = value;
                    this.RaisePropertyChanged("PempID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PregDate {
            get {
                return this.PregDateField;
            }
            set {
                if ((this.PregDateField.Equals(value) != true)) {
                    this.PregDateField = value;
                    this.RaisePropertyChanged("PregDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Premarks {
            get {
                return this.PremarksField;
            }
            set {
                if ((object.ReferenceEquals(this.PremarksField, value) != true)) {
                    this.PremarksField = value;
                    this.RaisePropertyChanged("Premarks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Psex {
            get {
                return this.PsexField;
            }
            set {
                if ((object.ReferenceEquals(this.PsexField, value) != true)) {
                    this.PsexField = value;
                    this.RaisePropertyChanged("Psex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string patientName {
            get {
                return this.patientNameField;
            }
            set {
                if ((object.ReferenceEquals(this.patientNameField, value) != true)) {
                    this.patientNameField = value;
                    this.RaisePropertyChanged("patientName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int patientNo {
            get {
                return this.patientNoField;
            }
            set {
                if ((this.patientNoField.Equals(value) != true)) {
                    this.patientNoField = value;
                    this.RaisePropertyChanged("patientNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Class_Checking", Namespace="http://schemas.datacontract.org/2004/07/HospitalCEFCService")]
    [System.SerializableAttribute()]
    public partial class Class_Checking : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime checkdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int docIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string feeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int patientNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string remarksField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime checkdate {
            get {
                return this.checkdateField;
            }
            set {
                if ((this.checkdateField.Equals(value) != true)) {
                    this.checkdateField = value;
                    this.RaisePropertyChanged("checkdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int docID {
            get {
                return this.docIDField;
            }
            set {
                if ((this.docIDField.Equals(value) != true)) {
                    this.docIDField = value;
                    this.RaisePropertyChanged("docID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fee {
            get {
                return this.feeField;
            }
            set {
                if ((object.ReferenceEquals(this.feeField, value) != true)) {
                    this.feeField = value;
                    this.RaisePropertyChanged("fee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int patientNo {
            get {
                return this.patientNoField;
            }
            set {
                if ((this.patientNoField.Equals(value) != true)) {
                    this.patientNoField = value;
                    this.RaisePropertyChanged("patientNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string remarks {
            get {
                return this.remarksField;
            }
            set {
                if ((object.ReferenceEquals(this.remarksField, value) != true)) {
                    this.remarksField = value;
                    this.RaisePropertyChanged("remarks");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Class_Test", Namespace="http://schemas.datacontract.org/2004/07/HospitalCEFCService")]
    [System.SerializableAttribute()]
    public partial class Class_Test : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string amountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int patientNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string remarksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime testdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string testheadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string amount {
            get {
                return this.amountField;
            }
            set {
                if ((object.ReferenceEquals(this.amountField, value) != true)) {
                    this.amountField = value;
                    this.RaisePropertyChanged("amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int patientNo {
            get {
                return this.patientNoField;
            }
            set {
                if ((this.patientNoField.Equals(value) != true)) {
                    this.patientNoField = value;
                    this.RaisePropertyChanged("patientNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string remarks {
            get {
                return this.remarksField;
            }
            set {
                if ((object.ReferenceEquals(this.remarksField, value) != true)) {
                    this.remarksField = value;
                    this.RaisePropertyChanged("remarks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime testdate {
            get {
                return this.testdateField;
            }
            set {
                if ((this.testdateField.Equals(value) != true)) {
                    this.testdateField = value;
                    this.RaisePropertyChanged("testdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string testhead {
            get {
                return this.testheadField;
            }
            set {
                if ((object.ReferenceEquals(this.testheadField, value) != true)) {
                    this.testheadField = value;
                    this.RaisePropertyChanged("testhead");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Class_Employee", Namespace="http://schemas.datacontract.org/2004/07/HospitalCEFCService")]
    [System.SerializableAttribute()]
    public partial class Class_Employee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int counterNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int empIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string empNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int counterNo {
            get {
                return this.counterNoField;
            }
            set {
                if ((this.counterNoField.Equals(value) != true)) {
                    this.counterNoField = value;
                    this.RaisePropertyChanged("counterNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int empID {
            get {
                return this.empIDField;
            }
            set {
                if ((this.empIDField.Equals(value) != true)) {
                    this.empIDField = value;
                    this.RaisePropertyChanged("empID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string empName {
            get {
                return this.empNameField;
            }
            set {
                if ((object.ReferenceEquals(this.empNameField, value) != true)) {
                    this.empNameField = value;
                    this.RaisePropertyChanged("empName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Class_Doctor", Namespace="http://schemas.datacontract.org/2004/07/HospitalCEFCService")]
    [System.SerializableAttribute()]
    public partial class Class_Doctor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string addressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contactField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int docIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string docNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string facultyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string address {
            get {
                return this.addressField;
            }
            set {
                if ((object.ReferenceEquals(this.addressField, value) != true)) {
                    this.addressField = value;
                    this.RaisePropertyChanged("address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contact {
            get {
                return this.contactField;
            }
            set {
                if ((object.ReferenceEquals(this.contactField, value) != true)) {
                    this.contactField = value;
                    this.RaisePropertyChanged("contact");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int docID {
            get {
                return this.docIDField;
            }
            set {
                if ((this.docIDField.Equals(value) != true)) {
                    this.docIDField = value;
                    this.RaisePropertyChanged("docID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string docName {
            get {
                return this.docNameField;
            }
            set {
                if ((object.ReferenceEquals(this.docNameField, value) != true)) {
                    this.docNameField = value;
                    this.RaisePropertyChanged("docName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string faculty {
            get {
                return this.facultyField;
            }
            set {
                if ((object.ReferenceEquals(this.facultyField, value) != true)) {
                    this.facultyField = value;
                    this.RaisePropertyChanged("faculty");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/HospitalCEFCService")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CEFCServiceReference.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Find", ReplyAction="http://tempuri.org/IService1/FindResponse")]
        hospital_mgmt_CEFC.CEFCServiceReference.Class_Patient Find(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/returntestcounter", ReplyAction="http://tempuri.org/IService1/returntestcounterResponse")]
        int returntestcounter();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/returncheckcounter", ReplyAction="http://tempuri.org/IService1/returncheckcounterResponse")]
        int returncheckcounter();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertNewPatients", ReplyAction="http://tempuri.org/IService1/InsertNewPatientsResponse")]
        string InsertNewPatients(hospital_mgmt_CEFC.CEFCServiceReference.Class_Patient pa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FindChecksofPatient", ReplyAction="http://tempuri.org/IService1/FindChecksofPatientResponse")]
        hospital_mgmt_CEFC.CEFCServiceReference.Class_Checking[] FindChecksofPatient(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FindChecksdonebyDoc", ReplyAction="http://tempuri.org/IService1/FindChecksdonebyDocResponse")]
        hospital_mgmt_CEFC.CEFCServiceReference.Class_Checking[] FindChecksdonebyDoc(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FindTestsofPatient", ReplyAction="http://tempuri.org/IService1/FindTestsofPatientResponse")]
        hospital_mgmt_CEFC.CEFCServiceReference.Class_Test[] FindTestsofPatient(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertNewEmployee", ReplyAction="http://tempuri.org/IService1/InsertNewEmployeeResponse")]
        string InsertNewEmployee(hospital_mgmt_CEFC.CEFCServiceReference.Class_Employee ce);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertNewDoctor", ReplyAction="http://tempuri.org/IService1/InsertNewDoctorResponse")]
        string InsertNewDoctor(hospital_mgmt_CEFC.CEFCServiceReference.Class_Doctor da);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateEmployee", ReplyAction="http://tempuri.org/IService1/UpdateEmployeeResponse")]
        string UpdateEmployee(hospital_mgmt_CEFC.CEFCServiceReference.Class_Employee ce);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdatePatient", ReplyAction="http://tempuri.org/IService1/UpdatePatientResponse")]
        string UpdatePatient(hospital_mgmt_CEFC.CEFCServiceReference.Class_Patient pa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateDoctor", ReplyAction="http://tempuri.org/IService1/UpdateDoctorResponse")]
        string UpdateDoctor(hospital_mgmt_CEFC.CEFCServiceReference.Class_Doctor da);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertNewTest", ReplyAction="http://tempuri.org/IService1/InsertNewTestResponse")]
        string InsertNewTest(hospital_mgmt_CEFC.CEFCServiceReference.Class_Test ct);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertNewChecking", ReplyAction="http://tempuri.org/IService1/InsertNewCheckingResponse")]
        string InsertNewChecking(hospital_mgmt_CEFC.CEFCServiceReference.Class_Checking cc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateMySQL", ReplyAction="http://tempuri.org/IService1/UpdateMySQLResponse")]
        string UpdateMySQL();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateSQL2008", ReplyAction="http://tempuri.org/IService1/UpdateSQL2008Response")]
        string UpdateSQL2008();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Fire2008", ReplyAction="http://tempuri.org/IService1/Fire2008Response")]
        string Fire2008();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        hospital_mgmt_CEFC.CEFCServiceReference.CompositeType GetDataUsingDataContract(hospital_mgmt_CEFC.CEFCServiceReference.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : hospital_mgmt_CEFC.CEFCServiceReference.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<hospital_mgmt_CEFC.CEFCServiceReference.IService1>, hospital_mgmt_CEFC.CEFCServiceReference.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public hospital_mgmt_CEFC.CEFCServiceReference.Class_Patient Find(int value) {
            return base.Channel.Find(value);
        }
        
        public int returntestcounter() {
            return base.Channel.returntestcounter();
        }
        
        public int returncheckcounter() {
            return base.Channel.returncheckcounter();
        }
        
        public string InsertNewPatients(hospital_mgmt_CEFC.CEFCServiceReference.Class_Patient pa) {
            return base.Channel.InsertNewPatients(pa);
        }
        
        public hospital_mgmt_CEFC.CEFCServiceReference.Class_Checking[] FindChecksofPatient(int id) {
            return base.Channel.FindChecksofPatient(id);
        }
        
        public hospital_mgmt_CEFC.CEFCServiceReference.Class_Checking[] FindChecksdonebyDoc(int id) {
            return base.Channel.FindChecksdonebyDoc(id);
        }
        
        public hospital_mgmt_CEFC.CEFCServiceReference.Class_Test[] FindTestsofPatient(int id) {
            return base.Channel.FindTestsofPatient(id);
        }
        
        public string InsertNewEmployee(hospital_mgmt_CEFC.CEFCServiceReference.Class_Employee ce) {
            return base.Channel.InsertNewEmployee(ce);
        }
        
        public string InsertNewDoctor(hospital_mgmt_CEFC.CEFCServiceReference.Class_Doctor da) {
            return base.Channel.InsertNewDoctor(da);
        }
        
        public string UpdateEmployee(hospital_mgmt_CEFC.CEFCServiceReference.Class_Employee ce) {
            return base.Channel.UpdateEmployee(ce);
        }
        
        public string UpdatePatient(hospital_mgmt_CEFC.CEFCServiceReference.Class_Patient pa) {
            return base.Channel.UpdatePatient(pa);
        }
        
        public string UpdateDoctor(hospital_mgmt_CEFC.CEFCServiceReference.Class_Doctor da) {
            return base.Channel.UpdateDoctor(da);
        }
        
        public string InsertNewTest(hospital_mgmt_CEFC.CEFCServiceReference.Class_Test ct) {
            return base.Channel.InsertNewTest(ct);
        }
        
        public string InsertNewChecking(hospital_mgmt_CEFC.CEFCServiceReference.Class_Checking cc) {
            return base.Channel.InsertNewChecking(cc);
        }
        
        public string UpdateMySQL() {
            return base.Channel.UpdateMySQL();
        }
        
        public string UpdateSQL2008() {
            return base.Channel.UpdateSQL2008();
        }
        
        public string Fire2008() {
            return base.Channel.Fire2008();
        }
        
        public hospital_mgmt_CEFC.CEFCServiceReference.CompositeType GetDataUsingDataContract(hospital_mgmt_CEFC.CEFCServiceReference.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
    }
}
