//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalCEFCService.SQL2008
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBchecking
    {
        public int docID { get; set; }
        public int patientNo { get; set; }
        public Nullable<System.DateTime> checkDate { get; set; }
        public string fee { get; set; }
        public string remarks { get; set; }
    
        public virtual DBdoctor doctor { get; set; }
        public virtual DBpatient patient { get; set; }
    }
}
