//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalCEFCService.SQL2008
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBemployee
    {
        public DBemployee()
        {
            this.patients = new HashSet<DBpatient>();
        }
    
        public int empID { get; set; }
        public string empName { get; set; }
        public int counterNo { get; set; }
    
        public virtual ICollection<DBpatient> patients { get; set; }
    }
}
