//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalCEFCService.SQL2008
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBpatient
    {
        public DBpatient()
        {
            this.checkings = new HashSet<DBchecking>();
        }
    
        public int patientNo { get; set; }
        public string PatientName { get; set; }
        public Nullable<int> age { get; set; }
        public string sex { get; set; }
        public string address { get; set; }
        public DateTime regDate { get; set; }
        public DateTime disDate { get; set; }
        public string remarks { get; set; }
        public int empID { get; set; }
    
        public virtual DBemployee employee { get; set; }
        public virtual DBtest test { get; set; }
        public virtual ICollection<DBchecking> checkings { get; set; }
    }
}
