//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalCEFCService.SQL2008
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBtest
    {
        public int patientNo { get; set; }
        public Nullable<System.DateTime> testdate { get; set; }
        public string testhead { get; set; }
        public string amount { get; set; }
        public string remarks { get; set; }
    
        public virtual DBpatient patient { get; set; }
    }
}
